name: check-for-msys2

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-2022
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: 'Check for msys2'
        shell: bash
        run: |
          ls C:/
