name: check-for-msys2

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-2022
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          update: false
          release: false
          install: make gcc
      - name: 'Check for msys2'
        shell: bash
        # C:/msys64/mingw64 is empty (only some dirs)
        run: |
          which gcc
